name: Build and push alpine base image
on:
  schedule:
    # monthly update
    - cron:  '0 0 1 * *'
  push:
    branches:
      - main
    paths:
      - base/alpine/3.13/Dockerfile
      - base/alpine/3.13/status.sh
      - base/alpine/3.13/motd
      - .github/workflows/alpine-linux.yaml
    workflow_dispatch:

env:
  IMAGE: alpine
  IMAGE_FOLDER: /base/${IMAGE}
  IMAGE_TAG_VERSION: 3.13
  IMAGE_CONTEXT: .${IMAGE_FOLDER}/3.13
  IMAGE_DOCKERFILE: ${IMAGE_CONTEXT}/Dockerfile

jobs:
  push:
    name: Build and push Alpine base

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./base/alpine/3.13/
          file: ./base/alpine/3.13/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: thecharge/alpine:3.13

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
