name: Build and push alpine Python 3.10 base image
on:
  push:
    branches:
      - main
    paths:
      - base/alpine/python/Dockerfile
      - .github/workflows/alpine-python.yaml
    workflow_dispatch:


jobs:
  push:
    name: Build and push Alpine base

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./base/alpine/python/
          file: ./base/alpine/python/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: thecharge/python:3.10-alpine

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
